# Build settings
markdown: kramdown

# Url structure 
permalink: /:categories/:title.html

baseurl: /blog

sass:
    sass_dir: css/_components

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
